### ISSUE TITLE
Tracking issue for cell2 impl 

### ISSUE THREAD

**Issue by 1024bees** [1024bees/wave2#3]
Tracking issue for the cell2 rewrite.

## API
```

let cell = Cell2::with_entries(
    Text::new("Wassup").width(Length::Fill).into(),
    &mut self.cell_state,
    vec![
        Entry::Item(Text::new("Test1").into(), Some(Message::Test1)),
        Entry::Group(
            Text::new("submenu").into(),
            vec![
                Entry::Item(Text::new("Test2").into(), Some(Message::Test2)),
                Entry::Item(Text::new("Test3").into(), Some(Message::Test3)),
                Entry::Group(
                    Text::new("submenu").into(),
                    vec![
                        Entry::Item(Text::new("Test2").into(), Some(Message::Test2)),
                        Entry::Item(Text::new("Test3").into(), Some(Message::Test3)),
                    ],
                ),
            ],
        ),
    ],
)
.set_single_click(|| Message::Toggle);
```

## Blockers

- [x]  Consistent Text API to control sizing per cell instantiation 
- [x]  Port over CellList to use cell2

## Motivation 

The previous implimentation (cell) suffered from two issues: bad test rendering, poor api for nested menus. Cell2 remedies these problems by leveraging `Text` widgets from iced native to handle rendering and using the `Entry` API to have a low level API to describe nested menus. 

For posterity, the previous effort to handle nested menus was through the implimentation of a `CellOption` trait that could be derived via proc macro. This approach ultimately failed due to the fact that it created an opaque abstraction that was hard to customize (e.g. toggable entries of menu, mutually exclusive entries of a menu, etc).

**Comment by 1024bees** [comment]
These initial blockers are cleared with `baaa4c002b68b855c67332846f86b3b065089846` 

Cell list now uses cell2. Also added the `LazyEntry` interface. LazyEntry allows menus to be stored with component state; previously we would transiently create menus within `view()`

text size apis have been added to `Cell2` in the form of `set_overlay_text_size`

Still there is still a little work that needs to be done on the cell2 front, but it is lower prio. what comes to mind is the following: 

* [ ] Spacing and padding apis for overlay text provided
* [ ] cell2 style brought up
* [ ] overlay location should spawn from right click
