### ISSUE TITLE
Tracking issue for wavewindow 

### ISSUE THREAD

**Issue by 1024bees** [1024bees/wave2#4]
Tracking issue for outstanding wavewindow issues. These are features I'd like to have merged prior leaving "pre-alpha".

Wavewindow (TODO: printscreen here) handles the visualization of digital signals.

- [ ] Cover X and Z signals viz
- [ ] Implement naive caching scheme on a per wave basis 
- [ ] Menu options impld per wave to handle color +  base
- [ ] Support interfaces MVP (todo: link to wavedb issue!)
