### ISSUE TITLE
Tracking issue for Hierarchy Navigator

### ISSUE THREAD

**Issue by 1024bees** [1024bees/wave2#5]
Pre-alpha blockers for the hierarchy navigator

TODO: put screenshot here. The hierarchy navigator is the widget that supports navigating the hierarchy of modules within a design.

- [ ] Test deeply nested hierarchies 
- [ ] Add options for displaying path
- [ ] move to cell2 impl
