### ISSUE TITLE
Tracking Issue for documentation and code sanitation

### ISSUE THREAD

**Issue by 1024bees** [1024bees/wave2#6]
Prealpha blockers for docs and code cleanliness. I want everything looking pretty before too many eyes peer into implimentation :) 

- [ ] Document wavedb interfaces 
     - [ ]  Droplet
     - [ ]  Puddle
     - [ ]  PuddleBuilder
     - [ ]  PCursor
     - [ ]  InMemWave
     - [ ] VCDConverter (TODO: check name i forgot what this type is called lol) 
- [ ] Document widgets
     - [ ] Wavewindow
     - [ ] Cell2
- [ ] Document Components 
     - [ ] Cell list
     - [ ] HierNav
     - [ ] ModNav
     - [ ] Beach
          - [ ] Wavewindow
          - [ ] Sigviewer
     - [ ] IconBar
     - [ ] MenuBar
 - [ ] Clean clippy output
 - [ ] No warnings when we cargo build / cargo test
