### ISSUE TITLE
Tracking issue for bringing up CI

### ISSUE THREAD

**Issue by 1024bees** [1024bees/wave2#7]
Tracking issue for CI implimentation effor

- [ ] Get a simple runner on base (my personal machine)
- [ ] Have simple workflow for running all unit tests 
- [ ] Add workflow for e2e tests wavedb tests (TODO: blocking on wavedb tracking issue)
- [ ] Add workflow for e2e gui tests (TODO: faraway, need tracking issue for iced testing shell)
