### ISSUE TITLE
Tracking issue for wavedb 

### ISSUE THREAD

**Issue by 1024bees** [1024bees/wave2#8]
Prealpha blockers for wavedb implimentation and testing strategy

- [ ] Remove Arc<Waverr> or derive clone for Waverr. Gross that Result<T, Arc<Waverr>> exsits.
- [ ] Add interface MVP (#9)
- [ ] Add bench tests for VCD parsing 
- [ ] Add e2e integration tests for multiple vcds
     - [ ] Add simple integration tests for `test_vcds/vga.vcd` and `test_vcds/test.vcd`
     - [ ] Generate medium ( > 100 MB) and large ( > 1 GB) sized traces on open source designs
     - [ ] Add integration tests for medium traces
     - [ ] Add integration tests for large traces
